### ISSUE TITLE
as3-ppt-to-swf-converter

### ISSUE THREAD

**Issue by byelik** [nidin/as3-ppt-to-swf-converter#2]
Hi. I'm working with you library - as3-ppt-to-swf-converter and I have a couple questions about it. 
1. My app crashes in that line of the code: System.setClipboard(HexUtils.dumpByteArray(pptBytes)); (PPT.as line 48)
2. In the READMY you have wrote: 'This project is not completed'. What exactly is not completed?
3. Where in the code I can get the result of the parsing .ppt file?
4. What version of the PowerPoint should I use?
5. Can I parse animation from PowerPoint file with your as3 library?

Thanks in advance.

**Comment by nidin** [comment]
I am no more developing this project.
You can use this base if you want to complete it.
The base is for parsing *.ppt binary format. checkout http://msdn.microsoft.com/en-us/library/office/cc313106(v=office.12).aspx

I encounter a problem with decompressing some binary blocks and i didn't invest much time to solve it.
right now i am working with javascript so no plan to continue this project may be i will port it to javascript if i got enough free time.

Don't hesitate to ask doubts.
