### ISSUE TITLE
how to run the project ?

### ISSUE THREAD

**Issue by VINO42** [nidin/as3-ppt-to-swf-converter#3]
can you write a  guide doc？

**Comment by nidin** [comment]
It's not 100% completed. I lost the track of the progress. There was some issue with decompressing PPT binary files. If you are just playing with it you can just compile `src\PPT2SWFConverter.as`. There is also a flashdevelop project file. If you are using windows, Just open it in [flashdevelop](http://www.flashdevelop.org/)

**Comment by VINO42** [comment]
thank u!
